# Generated by Django 4.2.3 on 2023-07-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskitem_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskitem", old_name="category", new_name="status",
        ),
    ]
