# Generated by Django 4.2.3 on 2023-07-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_category_taskitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskitem",
            name="elapsed_time",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskitem",
            name="estimated_time",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
