# Generated by Django 4.2.3 on 2023-07-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskitem_elapsed_time_taskitem_estimated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskitem",
            name="elapsed_time",
            field=models.IntegerField(default=0),
        ),
    ]
